import type { SpritesheetInit } from '../../types/index.js';
import { SpritesheetSet } from '../spritesheet-set.js';

const tileMeasures = {
  width: 32,
  height: 32,
} as const;

const tilesSpreadsheetMap = {
  'grass-full-tile': {
    x: 0,
    y: 0,
    ...tileMeasures,
  },
  'path-1': {
    x: 32,
    y: 0,
    ...tileMeasures,
  },
  'path-2': {
    x: 64,
    y: 0,
    ...tileMeasures,
  },
  'path-3': {
    x: 96,
    y: 0,
    ...tileMeasures,
  },
  'path-4': {
    x: 128,
    y: 0,
    ...tileMeasures,
  },
  'path-5': {
    x: 160,
    y: 0,
    ...tileMeasures,
  },
  'path-6': {
    x: 192,
    y: 0,
    ...tileMeasures,
  },
  // kinda useless
  // 'path-7': {
  //   x: 224,
  //   y: 0,
  //   ...tileMeasures,
  // },
  'path-8': {
    x: 256,
    y: 0,
    ...tileMeasures,
  },
  'path-9': {
    x: 288,
    y: 0,
    ...tileMeasures,
  },
  'path-10': {
    x: 320,
    y: 0,
    ...tileMeasures,
  },
  'path-11': {
    x: 352,
    y: 0,
    ...tileMeasures,
  },
  'path-12': {
    x: 384,
    y: 0,
    ...tileMeasures,
  },
  'path-13': {
    x: 416,
    y: 0,
    ...tileMeasures,
  },
  'path-14': {
    x: 448,
    y: 0,
    ...tileMeasures,
  },
  'path-15': {
    x: 480,
    y: 0,
    ...tileMeasures,
  },
  'path-16': {
    x: 512,
    y: 0,
    ...tileMeasures,
  },
  'path-17': {
    x: 544,
    y: 0,
    ...tileMeasures,
  },
  'path-18': {
    x: 576,
    y: 0,
    ...tileMeasures,
  },
  'path-19': {
    x: 608,
    y: 0,
    ...tileMeasures,
  },
  'path-20': {
    x: 640,
    y: 0,
    ...tileMeasures,
  },
  'path-21': {
    x: 672,
    y: 0,
    ...tileMeasures,
  },
  'path-22': {
    x: 704,
    y: 0,
    ...tileMeasures,
  },
  'path-23': {
    x: 736,
    y: 0,
    ...tileMeasures,
  },
  'path-24': {
    x: 768,
    y: 0,
    ...tileMeasures,
  },
  'path-25': {
    x: 800,
    y: 0,
    ...tileMeasures,
  },
  'path-26': {
    x: 832,
    y: 0,
    ...tileMeasures,
  },
  'path-27': {
    x: 864,
    y: 0,
    ...tileMeasures,
  },
  'path-28': {
    x: 896,
    y: 0,
    ...tileMeasures,
  },
  'path-29': {
    x: 928,
    y: 0,
    ...tileMeasures,
  },
  // kinda useless
  // 'path-30': {
  //   x: 960,
  //   y: 0,
  //   ...tileMeasures,
  // },
  'path-31': {
    x: 992,
    y: 0,
    ...tileMeasures,
  },
  'path-32': {
    x: 1024,
    y: 0,
    ...tileMeasures,
  },
  'path-33': {
    x: 1056,
    y: 0,
    ...tileMeasures,
  },
  'path-34': {
    x: 1088,
    y: 0,
    ...tileMeasures,
  },
  'path-35': {
    x: 1120,
    y: 0,
    ...tileMeasures,
  },
  'path-36': {
    x: 1152,
    y: 0,
    ...tileMeasures,
  },
  'path-37': {
    x: 1184,
    y: 0,
    ...tileMeasures,
  },
  'path-38': {
    x: 1216,
    y: 0,
    ...tileMeasures,
  },
  'path-39': {
    x: 1248,
    y: 0,
    ...tileMeasures,
  },
  'path-40': {
    x: 1280,
    y: 0,
    ...tileMeasures,
  },
  'path-41': {
    x: 1312,
    y: 0,
    ...tileMeasures,
  },
  'path-42': {
    x: 1344,
    y: 0,
    ...tileMeasures,
  },
  'path-43': {
    x: 1376,
    y: 0,
    ...tileMeasures,
  },
  'path-44': {
    x: 1408,
    y: 0,
    ...tileMeasures,
  },
  'path-45': {
    x: 1440,
    y: 0,
    ...tileMeasures,
  },
  'path-46': {
    x: 1472,
    y: 0,
    ...tileMeasures,
  },
  'path-47': {
    x: 1504,
    y: 0,
    ...tileMeasures,
  },
  'path-48': {
    x: 1536,
    y: 0,
    ...tileMeasures,
  },
} as const;

export type TileSpritesheetElementKey = Extract<keyof typeof tilesSpreadsheetMap, string>;

export type TilePathSpritesheetElementKey = Extract<
  keyof typeof tilesSpreadsheetMap,
  `path-${string}`
>;

export const pathTilesDirections = {
  top: [
    'path-2',
    'path-4',
    'path-5',
    'path-6',
    'path-8',
    'path-9',
    'path-10',
    'path-11',
    'path-12',
    'path-13',
    'path-14',
    'path-16',
    'path-17',
    'path-21',
    'path-23',
    'path-27',
    'path-28',
    'path-29',
    'path-31',
    'path-32',
    'path-33',
    'path-35',
    'path-36',
    'path-37',
    'path-40',
    'path-41',
    'path-42',
    'path-43',
    'path-44',
    'path-45',
    'path-46',
    'path-47',
  ],
  right: [
    'path-1',
    'path-3',
    'path-4',
    'path-5',
    'path-6',
    'path-8',
    'path-9',
    'path-12',
    'path-13',
    'path-14',
    'path-15',
    'path-17',
    'path-18',
    'path-19',
    'path-20',
    'path-21',
    'path-22',
    'path-24',
    'path-28',
    'path-29',
    'path-33',
    'path-34',
    'path-35',
    'path-37',
    'path-38',
    'path-39',
    'path-40',
    'path-41',
    'path-42',
    'path-43',
    'path-45',
    'path-46',
    'path-47',
  ],
  bottom: [
    'path-1',
    'path-2',
    'path-3',
    'path-4',
    'path-5',
    'path-6',
    'path-8',
    'path-11',
    'path-13',
    'path-14',
    'path-16',
    'path-17',
    'path-18',
    'path-19',
    'path-20',
    'path-21',
    'path-23',
    'path-26',
    'path-28',
    'path-29',
    'path-31',
    'path-32',
    'path-33',
    'path-34',
    'path-36',
    'path-37',
    'path-38',
    'path-39',
    'path-40',
    'path-41',
    'path-42',
    'path-43',
    'path-44',
    'path-45',
  ],
  left: [
    'path-2',
    'path-4',
    'path-5',
    'path-6',
    'path-8',
    'path-10',
    'path-11',
    'path-13',
    'path-15',
    'path-17',
    'path-18',
    'path-19',
    'path-20',
    'path-21',
    'path-22',
    'path-25',
    'path-28',
    'path-29',
    'path-32',
    'path-34',
    'path-35',
    'path-36',
    'path-38',
    'path-39',
    'path-40',
    'path-41',
    'path-42',
    'path-43',
    'path-44',
    'path-46',
    'path-47',
  ],
} satisfies Record<string, TilePathSpritesheetElementKey[]>;

const tilesSpritesheetSet: SpritesheetInit<TileSpritesheetElementKey> = {
  spritesheetKey: 'tiles-set',
  spritesheetPath: 'tiles-spritesheet',
  spritesheetMap: tilesSpreadsheetMap,
};

export const TilesSpritesheetSet =
  new SpritesheetSet<TileSpritesheetElementKey>(tilesSpritesheetSet);
